permissions:
  contents: write

name: Weekly Update Game News

on:
  schedule:
    # 每两周周一北京时间早上8点运行 (UTC时间0点)
    - cron: '0 0 */14 * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedparser

      - name: Run scraper and update data
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Auto-update: Bi-weekly news and data refresh"
          git push
